export interface MenuItem {
  slug: string;
  name: string;
  eyebrow: string; // mono label above the hero headline
  italTail: string; // italic teal phrase appended to the hero headline
  lede: string; // hero sub-paragraph
  sectionEyebrow: string; // eyebrow on the detail section
  body: string; // detail paragraph
  features: string[]; // checklist items
  cta: string; // primary CTA label
}

export interface MenuParent {
  key: string;
  route: string;
  label: string;
  items: MenuItem[];
}

export const MENU: MenuParent[] = [
  {
    key: "about",
    route: "/about",
    label: "About",
    items: [
      {
        slug: "story",
        name: "Company Overview",
        eyebrow: "ABOUT KLEZA",
        italTail: "what we believe.",
        lede: "Kleza is a fast-growing AI Transformation Company built to humanize technology and make intelligence accessible, ethical, and meaningful for every business.",
        sectionEyebrow: "WHO WE ARE",
        body: "We pair senior engineers, designers, and AI researchers with operators who actually run the workflows we improve. The result is AI that fits the way your teams already work — not a science project.",
        features: [
          "Founded on human-first AI",
          "Healthcare-deep expertise",
          "Senior, ships-fast team",
          "Outcome-led engagements",
          "Privacy by design",
          "Global delivery",
        ],
        cta: "Talk to our team",
      },
      {
        slug: "vision",
        name: "AI Transformation Vision",
        eyebrow: "OUR VISION",
        italTail: "engineered for the work of care.",
        lede: "A long-term roadmap for intelligence that augments practitioners, compounds in value, and stays accountable at every step.",
        sectionEyebrow: "THE ROADMAP",
        body: "We architect with reasoning models, agentic systems, and triangulated LLMs — not single-point bets. Every system we ship is designed to learn on purpose and to keep a human in the loop where it matters.",
        features: [
          "Agentic orchestration",
          "Multi-model reasoning",
          "Continuous evaluation",
          "Human-in-the-loop",
          "Measurable KPIs",
          "Responsible AI",
        ],
        cta: "Learn the vision",
      },
      {
        slug: "healthcare",
        name: "Healthcare Innovation",
        eyebrow: "75% HEALTHCARE FOCUS",
        italTail: "where decisions matter most.",
        lede: "The majority of our work lives in healthcare — intake, documentation, scheduling, and care coordination — where accuracy and trust are non-negotiable.",
        sectionEyebrow: "BUILT FOR CARE",
        body: "From HIPAA-aligned voice intake to documentation that takes a third of the time, we build for clinical context first. Models hand off to humans the moment they are uncertain.",
        features: [
          "HIPAA-aligned",
          "Clinical context",
          "EMR integration",
          "Documentation AI",
          "Care coordination",
          "Audit trails",
        ],
        cta: "See healthcare work",
      },
      {
        slug: "partnerships",
        name: "Partnerships",
        eyebrow: "BUILD WITH US",
        italTail: "let's build together.",
        lede: "We partner with health systems, agencies, and platforms to co-develop AI that ships and scales.",
        sectionEyebrow: "PARTNER PROGRAM",
        body: "Whether you bring distribution, data, or domain expertise, our partnership team will scope a model that creates value for both sides — with clear ownership and shared accountability.",
        features: [
          "Co-development",
          "White-label options",
          "Revenue sharing",
          "Joint go-to-market",
          "Dedicated team",
          "Clear ownership",
        ],
        cta: "Become a partner",
      },
      {
        slug: "careers",
        name: "Careers",
        eyebrow: "JOIN THE TEAM",
        italTail: "do work that matters.",
        lede: "We're always interested in curious engineers, designers, marketers, and operators who care about building AI that actually helps people.",
        sectionEyebrow: "OPEN ROLES",
        body: "Join a multidisciplinary crew of engineers, marketers, designers, AI researchers, IT operators, and outsourcing specialists working across India and beyond.",
        features: [
          "Engineering",
          "AI research",
          "Design",
          "Digital marketing",
          "Managed IT",
          "Operations",
        ],
        cta: "See open positions",
      },
    ],
  },
  {
    key: "ai-products",
    route: "/ai-products",
    label: "AI Products",
    items: [
      {
        slug: "voica",
        name: "Voica AI",
        eyebrow: "VOICE INTELLIGENCE",
        italTail: "conversation, refined.",
        lede: "Real-time conversational intelligence for intake, support, and care coordination — built for clinical context.",
        sectionEyebrow: "VOICE INTELLIGENCE",
        body: "Natural turn-taking, live transcription, and intelligent escalation. Voica hands off to a human whenever the model is uncertain, so nothing falls through the cracks.",
        features: [
          "Natural turn-taking",
          "HIPAA-aligned",
          "Multi-language",
          "Live transcript",
          "EMR integration",
          "Escalation routing",
        ],
        cta: "Book a Voica demo",
      },
      {
        slug: "pulse",
        name: "Pulse Board",
        eyebrow: "REAL-TIME OPS",
        italTail: "decisions, illuminated.",
        lede: "The operations dashboard that surfaces what's slipping before it slips — built for clinical and operational leaders.",
        sectionEyebrow: "OPS DASHBOARD",
        body: "Live KPI tiles, anomaly detection, and smart alerts in one role-based view. Pulse Board turns scattered signals into a single, trustworthy picture.",
        features: [
          "Live KPI tiles",
          "Smart alerts",
          "Anomaly detection",
          "Custom views",
          "Mobile-first",
          "Role-based",
        ],
        cta: "See Pulse Board",
      },
      {
        slug: "assessment",
        name: "Assessment App",
        eyebrow: "SMART ASSESSMENTS",
        italTail: "evaluation, simplified.",
        lede: "Digital assessments that adapt to the responder, score instantly, and route results where they need to go.",
        sectionEyebrow: "DIGITAL ASSESSMENTS",
        body: "Configurable templates, conditional logic, and instant scoring replace paper forms and manual tallies — with a clean audit trail for every submission.",
        features: [
          "Adaptive logic",
          "Instant scoring",
          "Custom templates",
          "Offline capture",
          "Analytics",
          "Export & API",
        ],
        cta: "Try Assessment App",
      },
      {
        slug: "onboarding",
        name: "Onboarding App",
        eyebrow: "END-TO-END ONBOARDING",
        italTail: "day one, done right.",
        lede: "End-to-end onboarding that collects documents, verifies details, and gets new people productive faster.",
        sectionEyebrow: "ONBOARDING",
        body: "Guided flows, automated document collection, and status tracking remove the back-and-forth from onboarding — for staff, caregivers, and clients alike.",
        features: [
          "Guided flows",
          "Document collection",
          "ID verification",
          "Status tracking",
          "E-signature",
          "Reminders",
        ],
        cta: "Streamline onboarding",
      },
      {
        slug: "docui",
        name: "DocUI",
        eyebrow: "DOCUMENT AI",
        italTail: "paperwork that flows.",
        lede: "Approve, sign, and route documents in one motion. DocUI reads, classifies, and routes paperwork through your workflows automatically.",
        sectionEyebrow: "DOCUMENT AI",
        body: "Auto-classification and intelligent routing turn an inbox of PDFs into a clean, auditable pipeline — with batch approval and e-signature built in.",
        features: [
          "Auto-classification",
          "E-signature",
          "Workflow routing",
          "Audit trail",
          "Batch approval",
          "Mobile-ready",
        ],
        cta: "Try DocUI",
      },
      {
        slug: "llms",
        name: "3 LLMs",
        eyebrow: "MULTI-MODEL REASONING",
        italTail: "three minds, one answer.",
        lede: "Triangulated reasoning across multiple models for answers you can trust — not single-point bets.",
        sectionEyebrow: "INTELLIGENCE SYSTEMS",
        body: "We orchestrate and cross-check multiple models, reconcile their outputs, and surface a confidence-scored answer with its reasoning intact.",
        features: [
          "Model triangulation",
          "Confidence scoring",
          "Orchestration",
          "Fallback routing",
          "Reasoning traces",
          "Cost control",
        ],
        cta: "Explore 3 LLMs",
      },
      {
        slug: "marketplace",
        name: "Marketplace",
        eyebrow: "INTEGRATIONS & TOOLS",
        italTail: "extend what you run.",
        lede: "Explore integrations, tools, templates, and AI-powered business solutions in one place.",
        sectionEyebrow: "MARKETPLACE",
        body: "Browse ready-to-deploy integrations and templates that connect Kleza products to the systems you already use — installable in minutes.",
        features: [
          "Integrations",
          "Templates",
          "Connectors",
          "One-click install",
          "Versioned",
          "Community-built",
        ],
        cta: "Browse Marketplace",
      },
      {
        slug: "hr",
        name: "HR Companion",
        eyebrow: "COMES360 · WORKFORCE",
        italTail: "people ops, handled.",
        lede: "Hiring, screening, and people-ops workflows handled with calm precision.",
        sectionEyebrow: "WORKFORCE COMPANION",
        body: "An agentic assistant that screens candidates, schedules interviews, and keeps people-ops moving — escalating to your team when judgement is needed.",
        features: [
          "Candidate screening",
          "Interview scheduling",
          "Onboarding handoff",
          "Policy answers",
          "Compliance prompts",
          "Analytics",
        ],
        cta: "Meet HR Companion",
      },
      {
        slug: "admin",
        name: "Admin Companion",
        eyebrow: "COMES360 · WORKFORCE",
        italTail: "operations, on autopilot.",
        lede: "Operational admin that takes the busywork off your team's plate.",
        sectionEyebrow: "WORKFORCE COMPANION",
        body: "From data entry to routine approvals and reporting, Admin Companion handles the repetitive back-office tasks so people can focus on the work that matters.",
        features: [
          "Task automation",
          "Approvals",
          "Reporting",
          "Data entry",
          "Reminders",
          "Audit logging",
        ],
        cta: "Meet Admin Companion",
      },
      {
        slug: "scheduler",
        name: "Scheduler Companion",
        eyebrow: "COMES360 · WORKFORCE",
        italTail: "shifts, in seconds.",
        lede: "Shifts, visits, and complex scheduling — assembled and re-shuffled in seconds.",
        sectionEyebrow: "WORKFORCE COMPANION",
        body: "Scheduler Companion balances availability, skills, and constraints to build conflict-free schedules, then re-optimizes instantly when something changes.",
        features: [
          "Auto-scheduling",
          "Conflict detection",
          "Skill matching",
          "Re-optimization",
          "Notifications",
          "Coverage view",
        ],
        cta: "Meet Scheduler Companion",
      },
      {
        slug: "caregiver",
        name: "Caregiver Companion",
        eyebrow: "COMES360 · CARE",
        italTail: "support at the bedside.",
        lede: "Direct-care AI that supports caregivers through onboarding, schedule, and day-to-day work.",
        sectionEyebrow: "CARE COMPANION",
        body: "A calm, on-call assistant for caregivers — answering questions, surfacing care plans, and logging visits without adding paperwork.",
        features: [
          "Care-plan access",
          "Visit logging",
          "Shift reminders",
          "Guided protocols",
          "Quick answers",
          "Hands-free",
        ],
        cta: "Meet Caregiver Companion",
      },
      {
        slug: "client",
        name: "Client Companion",
        eyebrow: "COMES360 · CARE",
        italTail: "engagement, made human.",
        lede: "Intelligent assistance built to improve client engagement experiences.",
        sectionEyebrow: "CLIENT COMPANION",
        body: "Client Companion keeps clients and families informed with timely, empathetic updates — and routes anything sensitive straight to a person.",
        features: [
          "Proactive updates",
          "Appointment reminders",
          "Family portal",
          "Sentiment-aware",
          "Smart escalation",
          "Multi-channel",
        ],
        cta: "Meet Client Companion",
      },
    ],
  },
  {
    key: "ai-services",
    route: "/ai-services",
    label: "AI Services",
    items: [
      {
        slug: "training",
        name: "Business-Specific AI Training",
        eyebrow: "CUSTOM TRAINING",
        italTail: "tuned to your reality.",
        lede: "Fine-tuning, RAG pipelines, and bespoke models built on your data, your terminology, your edge cases.",
        sectionEyebrow: "CUSTOM TRAINING",
        body: "We handle the whole path — data curation, fine-tuning, evaluation suites, and MLOps — so your models reflect how your business actually operates.",
        features: [
          "Data curation",
          "Fine-tuning",
          "RAG pipelines",
          "Evaluation suites",
          "Multi-model routing",
          "MLOps & monitoring",
        ],
        cta: "Scope your model",
      },
      {
        slug: "assistant",
        name: "AI Support Assistant",
        eyebrow: "SUPPORT",
        italTail: "always on, on-brand.",
        lede: "Conversational AI for 24/7 customer and operational support — trained on your knowledge base.",
        sectionEyebrow: "SUPPORT",
        body: "Tone-matched and multi-channel, the assistant escalates intelligently and learns from every interaction, with analytics built in from day one.",
        features: [
          "24/7 availability",
          "Multi-channel",
          "Tone-matched",
          "Smart escalation",
          "Continuous learning",
          "Analytics built-in",
        ],
        cta: "Talk to our team",
      },
      {
        slug: "automation",
        name: "End-to-End Business Process Automation",
        eyebrow: "PROCESS AUTOMATION",
        italTail: "from first trigger to final handoff.",
        lede: "Kleza maps the whole process — intake to invoice, referral to roster — and rebuilds it so the systems hand off to each other, and a person is only pulled in when judgement is genuinely required.",
        sectionEyebrow: "END-TO-END",
        body: "Automating one step just moves the bottleneck. We treat the process as one object — trigger, steps, decisions, exceptions, and the audit trail behind all of it — and run it after go-live, not just build it.",
        features: [
          "Process discovery & mapping",
          "Agentic orchestration",
          "Document intelligence",
          "Exception routing",
          "Human-in-the-loop approvals",
          "Run monitoring & audit trails",
        ],
        cta: "Map my processes",
      },
    ],
  },
  {
    key: "enterprise-services",
    route: "/enterprise-services",
    label: "Enterprise Services",
    items: [
      {
        slug: "web",
        name: "Website Development",
        eyebrow: "DIGITAL EXPERIENCE",
        italTail: "brand-grade, fast.",
        lede: "Modern, high-performance websites engineered for growth, engagement, and conversion.",
        sectionEyebrow: "DIGITAL EXPERIENCE",
        body: "From design systems to performance budgets, we build sites that load fast, rank well, and represent your brand with precision.",
        features: [
          "Design systems",
          "Performance-first",
          "SEO-ready",
          "Accessible",
          "CMS integration",
          "Analytics",
        ],
        cta: "Start a project",
      },
      {
        slug: "marketing",
        name: "Digital Marketing",
        eyebrow: "DIGITAL EXPERIENCE",
        italTail: "growth, on purpose.",
        lede: "Growth campaigns that combine creative, data, and automation to move the metrics that matter.",
        sectionEyebrow: "GROWTH",
        body: "We plan, launch, and optimize campaigns across channels — backed by measurement and AI-assisted content so spend turns into pipeline.",
        features: [
          "Paid & organic",
          "Content engine",
          "Campaign analytics",
          "A/B testing",
          "Attribution",
          "Automation",
        ],
        cta: "Plan a campaign",
      },
      {
        slug: "ops",
        name: "Operational Outsourcing",
        eyebrow: "OPERATIONAL SUPPORT",
        italTail: "scalable back-office.",
        lede: "Scalable back-office support that flexes with your business and frees your team to focus.",
        sectionEyebrow: "OPERATIONS",
        body: "A trained, accountable team handles your repeatable operations with documented processes, SLAs, and AI tooling that keeps quality high as you scale.",
        features: [
          "Trained teams",
          "Documented SOPs",
          "SLA-backed",
          "AI-assisted",
          "Flexible capacity",
          "Quality assurance",
        ],
        cta: "Scope outsourcing",
      },
      {
        slug: "it",
        name: "Remote IT Services",
        eyebrow: "OPERATIONAL SUPPORT",
        italTail: "infrastructure, cared for.",
        lede: "24/7 infrastructure care — monitoring, maintenance, and support that keeps you running.",
        sectionEyebrow: "MANAGED IT",
        body: "Proactive monitoring, patching, and remote support across your stack, with clear escalation and response times you can count on.",
        features: [
          "24/7 monitoring",
          "Patch management",
          "Remote support",
          "Backup & recovery",
          "Security hardening",
          "Asset tracking",
        ],
        cta: "Talk to IT",
      },
      {
        slug: "blog",
        name: "Blog Automation",
        eyebrow: "CONTENT AUTOMATION",
        italTail: "publishing on autopilot.",
        lede: "AI tools that automate content workflows, publishing, and distribution end to end.",
        sectionEyebrow: "CONTENT AUTOMATION",
        body: "From brief to published post, Blog Automation drafts, optimizes, and schedules content on brand — with a human review gate before anything goes live.",
        features: [
          "AI drafting",
          "SEO optimization",
          "Scheduling",
          "Review gate",
          "Multi-site",
          "Performance tracking",
        ],
        cta: "Automate content",
      },
      {
        slug: "social",
        name: "Social Media Scheduling",
        eyebrow: "CONTENT AUTOMATION",
        italTail: "right post, right time.",
        lede: "Multi-channel scheduling that plans, queues, and posts at the moments that perform.",
        sectionEyebrow: "SOCIAL",
        body: "Plan a calendar across every channel, auto-generate variants, and let the scheduler post at optimal times — with analytics to close the loop.",
        features: [
          "Multi-channel",
          "Content calendar",
          "Best-time posting",
          "Variant generation",
          "Approvals",
          "Analytics",
        ],
        cta: "Schedule smarter",
      },
      {
        slug: "serp",
        name: "SERP Agent",
        eyebrow: "SEARCH & VISIBILITY",
        italTail: "ranks, watched.",
        lede: "Search rank monitoring that tracks visibility and flags movement before it costs you traffic.",
        sectionEyebrow: "SEARCH INTELLIGENCE",
        body: "SERP Agent tracks your keywords across locations and devices, detects ranking shifts, and surfaces the opportunities and risks that matter.",
        features: [
          "Rank tracking",
          "Competitor watch",
          "Movement alerts",
          "Local & device",
          "Opportunity finder",
          "Reports",
        ],
        cta: "Track your rankings",
      },
      {
        slug: "indexing",
        name: "Auto Indexing",
        eyebrow: "SEARCH & VISIBILITY",
        italTail: "indexed instantly.",
        lede: "Instant search updates that get new and changed pages indexed without the wait.",
        sectionEyebrow: "SEARCH INTELLIGENCE",
        body: "Auto Indexing submits and verifies your URLs the moment they change, so search engines see your freshest content first.",
        features: [
          "Instant submission",
          "Change detection",
          "Index verification",
          "Sitemap sync",
          "Bulk URLs",
          "Status reports",
        ],
        cta: "Speed up indexing",
      },
      {
        slug: "domain",
        name: "Domain Expiry Verification",
        eyebrow: "MONITORING & VERIFICATION",
        italTail: "never miss a renewal.",
        lede: "Continuous checks so a forgotten renewal never takes your site offline.",
        sectionEyebrow: "MONITORING",
        body: "We watch your domains and certificates, and alert the right people well ahead of any expiry — with a clear dashboard of what's due when.",
        features: [
          "Expiry monitoring",
          "SSL checks",
          "Early alerts",
          "Multi-domain",
          "Renewal calendar",
          "Escalation",
        ],
        cta: "Protect your domains",
      },
      {
        slug: "perf",
        name: "Website Performance Verification",
        eyebrow: "MONITORING & VERIFICATION",
        italTail: "uptime & speed, proven.",
        lede: "Continuous uptime and speed checks that keep your digital surface reliable.",
        sectionEyebrow: "MONITORING",
        body: "Synthetic and real-user checks measure availability and Core Web Vitals around the clock, alerting you the instant performance slips.",
        features: [
          "Uptime monitoring",
          "Core Web Vitals",
          "Synthetic checks",
          "Real-user metrics",
          "Incident alerts",
          "Trend reports",
        ],
        cta: "Monitor performance",
      },
    ],
  },
  {
    key: "resources",
    route: "/resources",
    label: "Resources",
    items: [
      {
        slug: "newsletter",
        name: "Newsletters",
        eyebrow: "INSIGHTS & UPDATES",
        italTail: "intelligence, monthly.",
        lede: "A monthly intelligence digest on applied AI, healthcare, and digital operations.",
        sectionEyebrow: "NEWSLETTERS",
        body: "Short, useful, and free of hype — our newsletter distills what's actually working in AI for teams that build and operate.",
        features: [
          "Monthly digest",
          "Applied AI",
          "Case studies",
          "No spam",
          "One-click unsubscribe",
          "Archive access",
        ],
        cta: "Subscribe",
      },
      {
        slug: "articles",
        name: "Blogs",
        eyebrow: "INSIGHTS & UPDATES",
        italTail: "essays & case studies.",
        lede: "Long-form essays and case studies on building AI that actually helps people.",
        sectionEyebrow: "BLOGS",
        body: "Deep dives into architecture decisions, real deployments, and the outcomes they produced — written by the people who shipped them.",
        features: [
          "Long-form essays",
          "Case studies",
          "Architecture notes",
          "Outcomes & KPIs",
          "Practitioner-written",
          "Searchable",
        ],
        cta: "Read the blog",
      },
    ],
  },
  {
    key: "contact",
    route: "/contact",
    label: "Contact",
    items: [
      {
        slug: "schedule",
        name: "Schedule a Consultation",
        eyebrow: "GET IN TOUCH",
        italTail: "pick a 30-min slot.",
        lede: "Book a focused 30-minute consultation with our team to scope your AI or digital project.",
        sectionEyebrow: "CONSULTATION",
        body: "Come with a problem, leave with a plan. We'll map your workflow, surface the highest-leverage AI opportunities, and outline what a first engagement looks like.",
        features: [
          "30-minute call",
          "Workflow mapping",
          "Opportunity scan",
          "Clear next steps",
          "No obligation",
          "Senior team",
        ],
        cta: "Book a slot",
      },
      {
        slug: "experts",
        name: "Talk to Experts",
        eyebrow: "GET IN TOUCH",
        italTail: "a direct line.",
        lede: "A direct line to a solutions architect who can answer the hard questions.",
        sectionEyebrow: "EXPERTS",
        body: "Skip the sales script. Talk technical specifics — models, integrations, data, and deployment — with someone who has actually built and shipped them.",
        features: [
          "Solutions architects",
          "Technical depth",
          "Integration advice",
          "Architecture review",
          "Security & compliance",
          "Fast response",
        ],
        cta: "Talk to an expert",
      },
      {
        slug: "form",
        name: "Contact Form",
        eyebrow: "GET IN TOUCH",
        italTail: "send us a message.",
        lede: "Send us a message and we'll get back to you within one business day.",
        sectionEyebrow: "MESSAGE US",
        body: "Tell us a little about what you're working on. The more context you share, the more useful our first reply will be.",
        features: [
          "One business day",
          "Routed to the right team",
          "Confidential",
          "No spam",
          "Attach details",
          "Global coverage",
        ],
        cta: "Open the form",
      },
    ],
  },
];

export function getParent(key: string): MenuParent | undefined {
  return MENU.find((p) => p.key === key);
}

export function getItem(key: string, slug: string): MenuItem | undefined {
  return getParent(key)?.items.find((i) => i.slug === slug);
}
